import 'package:doc_app/Components/Doctor.dart';

List<Doctor> kDoctorList = [
  Doctor(
    name: "Dr. Harsh Kulkarni",
    profession: "Therapist",
    rating: 4,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe:
        "Your mom so fat Thanos had to clap. Your mom so fat Thanos had to clap. Your mom so fat Thanos had to clap. Your mom so fat Thanos had to clap. Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Dr. Aniket Kharpatil",
    profession: "Pediatrician",
    rating: 4.1,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Dr. Purvaja Kale",
    profession: "Ophthalmologist",
    rating: 4.5,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Dr XYZ",
    profession: "Crapologist",
    rating: 3,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Yo mom",
    profession: "lorem ipsum",
    rating: 4.9,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Barack Obama",
    profession: "Democratic",
    rating: 4.1,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
  Doctor(
    name: "Joe Biden",
    profession: "President of Murica",
    rating: 4.9,
    urlToImage: "https://source.unsplash.com/random",
    aboutMe: "Your mom so fat Thanos had to clap",
    price: 2000,
    phNo: 69999999105,
    location: "St. Peter's Hospital, Versova, Mumbai",
  ),
];
